### ISSUE TITLE
SCT: 404 News

### ISSUE THREAD

**Issue by DragonRulerX** [Tharylia/Blish-HUD-Modules#79]
**Describe the bug**
```
03:25:35.2270 | DEBUG | Estreya.BlishHUD.Shared.Services.NewsService | Failed to load news:
Flurl.Http.FlurlHttpException: Call failed with status code 404 (Not Found): GET https://files.estreya.de/blish-hud/scrolling-combat-text/news.json
   at Flurl.Http.FlurlRequest.<HandleExceptionAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Flurl.Http.FlurlRequest.<SendAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Flurl.Http.FlurlRequest.<SendAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Flurl.Http.HttpResponseMessageExtensions.<ReceiveString>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Estreya.BlishHUD.Shared.Services.NewsService.<Load>d__12.MoveNext() in C:\BhApps\BhudRequestFor\work\8vMp0ksw1kudwFndaTjtuQ\Estreya.BlishHUD.Shared\Services\NewsService.cs:line 49
   ```

**To Reproduce**
1. I think just have the SCT module installed and load blish?

**Expected behavior**
Should not see error in log file.

**Screenshots**
N/A

**Error Submission Module**
I don't think so?

**Additional context**
This error fits in the logs between these two events which may or may not be related?
```
03:25:33.4832 | DEBUG | Blish_HUD.ArcDps.SocketListener | Connected.
...
03:25:35.4978 | WARN  | Blish_HUD.ArcDps.SocketListener | ConnectionRefused
```

**Comment by Tharylia** [comment]
It's an expected message for now.
That's why it's logged as DEBUG and not ERROR.

I have added the file. If you restart blish you shouldn't be seeing that message anymore.

**Comment by DragonRulerX** [comment]
Indeed - the error is now gone. Impressive turn around time :D
Unfortunately, it did not fix my ArcDPS issue, but I don't want to hijack your repo for diagnosing what's wrong since it's likely unrelated to any of these modules. I shall keep digging. Beginning to think it's a file permissions issue perhaps.

**Comment by Tharylia** [comment]
Its just a small file on my fileserver. If there are no news I just don't bother to put it there 😄
